AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template for deployment of CVT - Upfit

Mappings:
  SourceCode:
    General:
      S3Bucket: "cvt-iot-250"
      KeyPrefix: "dist"

Resources:
  CVTUpfitFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "AWS Connected Vehicle Upfit Solution deployment "
      Code:
        S3Bucket: !FindInMap ["SourceCode", "General", "S3Bucket"]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"],  "app.zip"]]
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: !Sub "${AWS::StackName}-cvt-upfit-function"
      MemorySize: 512
      Runtime: python3.7
      Timeout: 300
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - "sts:AssumeRole"
      Path: "/"
      # Create a policy attached to the role
      # Allow Cloudwatch logging
      Policies:
      - PolicyName: "AllowLogging"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*    