AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template for deployment of CVT - SmartBox


Parameters: # params passed to "--parameter-overrides" in CLI
  AppVersion:
    Description: Unique app version
    Type: String

Mappings:
  SourceCode:
    General:
      S3Bucket: "cvt-iot-250"
      KeyPrefix: "dist"

Resources:
  CVTSmartBoxFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "AWS Connected Vehicle SmartBox Solution deployment "
      Code:
        S3Bucket: !FindInMap ["SourceCode", "General", "S3Bucket"]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"], !Ref AppVersion, "app.zip"] ]
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: !Sub "${AWS::StackName}-SmartBox-function"
      MemorySize: 512
      Runtime: python3.7
      Timeout: 300
  version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref CVTSmartBoxFunction
      Description: !Ref AppVersion  
  alias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref CVTSmartBoxFunction
      FunctionVersion: !GetAtt version.Version
      Name: dev
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - "sts:AssumeRole"
      Path: "/"
      # Create a policy attached to the role
      # Allow Cloudwatch logging
      Policies:
      - PolicyName: "AllowLogging"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:* 

Outputs:
  CVTSmartBoxFunctionARN:
    Description: ARN of CVTSmartBoxFunction created lambda function
    Value: !Ref CVTSmartBoxFunction